version: '3.4'

services:
  ultratic:
    image: ultratic
    build:
      context: ultra-tic
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://user:password@db:5432/ultraticdb
    ports:
      - 3000:3000
    networks:
      - pgnetwork
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: ultratic_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ultraticdb
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data  # Bind mount for your data
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 3001:80  # Exposing pgAdmin on port 3001 locally
    volumes:
      - ./volumes/pgadmin/pgadmin:/var/lib/pgadmin  # Persist pgAdmin configuration
    networks:
      - pgnetwork
    depends_on:
      - db

networks:
  pgnetwork:
    driver: bridge