apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      # optional: do a sts:assumeRole before fetching secrets
      role: external-secrets-irsa