---
- name: Install Packages
  hosts: localhost
  become: yes
  tasks:
    - name: Install PostgreSQL packages
      yum:
        name: postgresql-server
        state: present

    - name: Initialize PostgreSQL database
      command: postgresql-setup initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.conf

    - name: Update listen_addresses in postgresql.conf
      lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        regexp: '^#?listen_addresses ='
        line: "listen_addresses = '*'"
        state: present

    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Ensure pip is installed
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install boto and boto3 using pip
      ansible.builtin.pip:
        name:
          - boto
          - boto3
        state: present

    - name: Install community.postgresql collection
      ansible.builtin.ansible-galaxy:
        command: "collection install"
        name: "community.postgresql"