---
- name: Install Packages
  hosts: localhost
  become: yes
  tasks:
    - name: Install needed packages
      yum:
        name: 
          - postgresql15-server
          - cronie
          - python3-pip
        state: present

    - name: Initialize PostgreSQL database
      command: postgresql-setup initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.conf

    - name: Update listen_addresses in postgresql.conf
      lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        regexp: '^#?listen_addresses ='
        line: "listen_addresses = '*'"
        state: present

    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Install python dependencies using pip
      ansible.builtin.pip:
        name:
          - boto
          - boto3
          - psycopg2
        state: present