---
- name: Install PostgreSQL
  hosts: postgres
  become: yes
  tasks:
    - name: Install PostgreSQL packages
      yum:
        name: postgresql-server
        state: present

    - name: Initialize PostgreSQL database
      command: postgresql-setup initdb

    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: yes