---
- name: Setup PostgreSQL access
  hosts: localhost
  become: yes
  tasks:
    - name: Allow access from VPC CIDR range in pg_hba.conf
      community.postgresql.postgresql_pg_hba:
        dest: "/var/lib/pgsql/data/pg_hba.conf" 
        contype: "host"                        # Type: local, host, hostssl, etc.
        users: all                             # PostgreSQL users
        source: "{{ vpc_cidr }}"               # CIDR or IP for source
        databases: all                         # Target database
        method: "md5"                          # Authentication method

    - name: Reload PostgreSQL configuration
      ansible.builtin.service:
        name: postgresql
        state: reloaded

    - name: Retrieve postgres secret
      set_fact:
        postgres_secret: "{{ lookup('amazon.aws.aws_secret', postgres_secret_name, region=aws_region) }}"

    - name: Create postgres database
      community.postgresql.postgresql_db:
        name: "{{ postgres_secret.db }}"
      become_user: postgres

    - name: Create postgres user exists with credentials
      community.postgresql.postgresql_user:
        name: "{{ postgres_secret.username }}"
        password: "{{ postgres_secret.password }}"
        db: "{{ postgres_secret.db }}"
        state: present
      become_user: postgres

    - name: Grant user privileges to created database
      community.postgresql.postgresql_privs:
        db: "{{ postgres_secret.db }}"
        privs: ALL
        type: schema
        objs: public
        role: "{{ postgres_secret.username }}"
      become_user: postgres