---
- name: Restrict PostgreSQL access to VPC CIDR range
  hosts: postgres
  become: yes
  tasks:
    - name: Allow access from VPC CIDR range in pg_hba.conf
      lineinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        regexp: '^#.*allow access from VPC'
        line: "host    all             all             {{ vpc_cidr }}       md5"
        insertafter: EOF

    - name: Reload PostgreSQL to apply new access rules
      systemd:
        name: postgresql
        state: reloaded